#!/bin/bash
SVCPID=`ps ax | grep runCamera | grep -v grep | cut -c -6 | sed -e 's/ *//g'`
sudo svc -d /service/camera
if [[ ! -z $SVCPID ]]; then
        sudo kill $SVCPID
        sleep 1
        sudo kill -9 $SVCPID
        sleep 1
fi
exec ./runCamera
