#!/bin/sh
#/etc/init.d/rename-on-boot
### BEGIN INIT INFO
# Provides:          rename-on-boot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 1 2 3 4 5
# Default-Stop: 
# Short-Description: Change AP SSID on boot
# Description: On boot this script takes an SSID value set in config.txt and changes the Network Manager profile to this value. This may be a rather blunt solution but if it works it works.
### END INIT INFO

SSID=$(grep -oP "ssid=\K.*" /boot/config.txt)

sed -i "s,$(grep -oP "ssid=\K.*" /etc/NetworkManager/system-connections/WiFiAP.nmconnection),$SSID," /etc/NetworkManager/system-connections/WiFiAP.nmconnection