#!/bin/sh
#/etc/init.d/rename-on-boot
### BEGIN INIT INFO
# Provides:          rename-on-boot
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 1 2 3 4 5
# Default-Stop: 
# Short-Description: Change AP SSID on boot
# Description: On boot this script takes an SSID value set in config.txt and changes the Network Manager profile to this value. This may be a rather blunt solution but if it works it works.
### END INIT INFO

ssid_rename () {
APNAME="WiFiAP"
SSID=$(grep -oP "ssid=\K.*" /boot/config.txt)

sudo nmcli connection down $APNAME
sudo nmcli connection modify $APNAME ssid "$SSID"
sudo nmcli connection up $APNAME
}

case "$1" in
    start)
        ssid_rename
    ;;
    stop)
       stop 
    ;;
    *)
exit 1
;;
esac
