#!/bin/bash -x

source /etc/farm-environment
SCRIPT_NAME=$1
while true; do
    timeout 10 wget -nv -O /tmp/${SCRIPT_NAME} ${CONFIG_URL}/${SCRIPT_NAME} && break
    sleep 5
done
chmod +x "/tmp/${SCRIPT_NAME}"
