#!/bin/bash -e

mkdir -p "${ROOTFS_DIR}/boot/firmware"

if ! [ -L "${ROOTFS_DIR}/boot/overlays" ]; then
	ln -s firmware/overlays "${ROOTFS_DIR}/boot/overlays"
fi

install -m 644 files/cmdline.txt "${ROOTFS_DIR}/boot/firmware/"
sed -i "s|FILE_SYSTEM_TYPE|${FILE_SYSTEM_TYPE}|" "${ROOTFS_DIR}/boot/firmware/cmdline.txt"
if [ "${FILE_SYSTEM_TYPE}" == "btrfs" ]; then
	ROOT_FLAGS="rootflags=subvol=@"
fi
sed -i "s|ROOT_FLAGS|${ROOT_FLAGS}|" "${ROOTFS_DIR}/boot/firmware/cmdline.txt"

install -m 644 files/config.txt "${ROOTFS_DIR}/boot/firmware/"

for file in cmdline.txt config.txt; do
	printf "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to %s\n" "/boot/firmware/${file}" > "${ROOTFS_DIR}/boot/${file}"
done
