#! /bin/sh

### BEGIN INIT INFO
# Provides:          drideOS-resize
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: will resize the file system & reboot
# Description:       
### END INIT INFO

echo "dwc_otg.lpm_enable=0  console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4  elevator=deadline fsck.repair=yes   rootwait" > /boot/cmdline.txt

# Delete the script
rm $0
# reboot
sudo reboot