# This is a basic workflow to help you get started with Actions

name: Build yunohost rpi image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "yunohost-buster" branch
  push:
    branches: [ "yunohost-bullseye" ]
  pull_request:
    branches: [ "yunohost-bullseye" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt update
          apt-get -y install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          ./build-docker.sh
          
