# This is a basic workflow to help you get started with Actions

name: pi-gen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pi-gen-upload-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: "podman-custom"
          use-qcow2: 1
          compression: "gz"
          locale: "en_US.UTF-8"
          keyboard-keymap: "us"
          keyboard-layout: "English (US)"
          timezone: "America/Chicago"

      - uses: actions/upload-artifact@v3
        with:
          name: custom-image
          path: ${{ steps.build.outputs.image-path }}
          
